Fix consumer of python queue size is zero (#5706)
Fixes https://github.com/apache/pulsar/issues/5634


Master Issue: https://github.com/apache/pulsar/issues/5634

### Motivation

In java clients, when we call the `receive`, we will block it until a message arrives. in python clients, when we call the `receive` function, we add a delay parameter of 100ms. when the queue size is 0, the `receive` will have a strict check on the queue size, causing the following exception to be thrown

```
Traceback (most recent call last):
  File "tst.py", line 10, in <module>
    msg = consumer.receive()
  File "/python3.7/site-packages/pulsar/__init__.py", line 930, in receive
    msg = self._consumer.receive()
Exception: Pulsar error: InvalidConfiguration
```
### Modifications

* Removing timeout parameter in synchronous `receive`
* Add test for queue size is 0

### Verifying this change

Add Test